### ISSUE TITLE
Plays nice with dataparallel?

### ISSUE THREAD

**Issue by thomasflynn918** [pytorch/opacus#27]
Hello, is the imagenet example code known to play well with DataParallel?
I got the following error when trying to train with multiple GPUs:

` $ CUDA_VISIBLE_DEVICES=0,1,2,3 python imagenet.py --lr 0.1 --sigma 0.5 -c 1.5 --batch-size 256 --epochs 10 . --workers 32`

Output is

PRIVACY ENGINE ON
Traceback (most recent call last):
  File "imagenet.py", line 652, in <module>
    main()
  File "imagenet.py", line 275, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "imagenet.py", line 442, in main_worker
    train(train_loader, model, criterion, optimizer, epoch, args)
  File "imagenet.py", line 509, in train
    optimizer.step()
  File "/home/tflynn/pylocal/lib/python3.7/site-packages/torchdp/privacy_engine.py", line 73, in dp_step
    self.privacy_engine.step()
  File "/home/tflynn/pylocal/lib/python3.7/site-packages/torchdp/privacy_engine.py", line 98, in step
    clip_values = self.clipper.step()
  File "/home/tflynn/pylocal/lib/python3.7/site-packages/torchdp/per_sample_gradient_clip.py", line 206, in step
    autograd_grad_sample.compute_grad_sample(self.module, batch_dim=self.batch_dim)
  File "/home/tflynn/pylocal/lib/python3.7/site-packages/torchdp/autograd_grad_sample.py", line 153, in compute_grad_sample
    _check_layer_sanity(layer)
  File "/home/tflynn/pylocal/lib/python3.7/site-packages/torchdp/autograd_grad_sample.py", line 121, in _check_layer_sanity
    f"No activations detected for {type(layer)},"
ValueError: No activations detected for <class 'torch.nn.modules.conv.Conv2d'>, run forward after add_hooks(model)

However, there is no issue when using 1 GPU.

**Comment by Darktex** [comment]
Thanks for reporting! Yes, currently we do not support parallel training (DP nor DDP). It is however on the list of things we are going to work on! We are currently doing some cleaning of the API and polishing of the docs, but this is indeed at the top of our list :)

**Comment by YongGuCheng** [comment]
@Darktex

**Comment by YongGuCheng** [comment]
@Darktex 
Hi Davide, do we have Opacus with parallel training (DP or DDP) now (as of today)?

**Comment by Darktex** [comment]
No, not yet

**Comment by alexandresablayrolles** [comment]
Closing the issue as we now have DDP in Opacus.

**Comment by Yuancheng-Xu** [comment]
Hi, is DP also supported ?
