### ISSUE TITLE
AttributeError: 'Parameter' object has no attribute '_current_grad_sample'

### ISSUE THREAD

**Issue by AdhirajSingh1206** [pytorch/opacus#405]
## 🐛 Bug

This appears when i run it on a modified resnet 50. 
Thanks in advance. 

Traceback (most recent call last):
  File "/hdd4/DA_Adhiraj/SFDA_neighbors/office-home/train_src.py", line 266, in <module>
    train_source(args)
  File "/hdd4/DA_Adhiraj/SFDA_neighbors/office-home/train_src.py", line 132, in train_source
    loss.backward()
  File "/home/anil/anaconda3/envs/asingh/lib/python3.9/site-packages/torch/_tensor.py", line 363, in
backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/anil/anaconda3/envs/asingh/lib/python3.9/site-packages/torch/autograd/__init__.py", lin
e 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/anil/anaconda3/envs/asingh/lib/python3.9/site-packages/opacus/grad_sample/grad_sample_m
odule.py", line 338, in capture_backprops_hook
    promote_current_grad_sample(p)
  File "/home/anil/anaconda3/envs/asingh/lib/python3.9/site-packages/opacus/grad_sample/grad_sample_$
odule.py", line 55, in promote_current_grad_sample
    p.grad_sample = p._current_grad_sample
AttributeError: 'Parameter' object has no attribute '_current_grad_sample'

**Comment by AS-vg** [comment]
Could you tell me how did you solve this problem?
